### ISSUE TITLE
Conversions to CString without nul byte

### ISSUE THREAD

**Issue by mstange** [nicholasbishop/rust-conversions#1]
Hi,

The comment above conversion to `CStr` says: "If your input is not nul-terminated then a conversion without allocation is not possible, convert to a CString instead."
But then all the suggested conversions to CString just convert to a CStr first. So if the input is not nul-terminated, the suggested conversion to CString also fails.

It looks like `CString::new(input)` would be the right answer for most of these - it adds the nul-terminater if it's not present.

**Comment by nicholasbishop** [comment]
Thanks for reporting that :) Should be fixed now.

**Comment by mstange** [comment]
Nice, thanks!
